library(myfibo)

a = TypeClass()
invisible(a$setInt(12))
i = a$getInt()
cat(class(i),"\n")
if (i != 12)
  cat("Wrong int!","\n")
cat(i,"\n")
invisible(a$setDouble(5.67))
d = a$getDouble()
cat(class(d),"\n")
if (d != 5.67)
  cat("Wrong double!","\n")
cat(d,"\n")
invisible(a$setString("Str12"))
s = a$getString()
cat(class(s),"\n")
if (s != "Str12")
  cat("Wrong String!","\n")
cat(s,"\n")
invisible(a$setVectorInt(c(23,33,43)))
vi = a$getVectorInt()
cat(class(vi),"\n")
if (vi[1] != 23 || vi[2] != 33 || vi[3] != 43)
  cat("Wrong VectorInt!","\n")
cat(vi,"\n")
invisible(a$setVectorDouble(c(5.67,6.78,7.89)))
vd = a$getVectorDouble()
cat(class(vd),"\n")
if (vd[1] != 5.67 || vd[2] != 6.78 || vd[3] != 7.89)
  cat("Wrong VectorDouble!","\n")
cat(vd,"\n")
invisible(a$setVectorString(c("Str23","Str33","Str43")))
vs = a$getVectorString()
cat(class(vs),"\n")
if (vs[1] != "Str23" || vs[2] != "Str33" || vs[3] != "Str43")
  cat("Wrong VectorString!","\n")
cat(vs,"\n")