name: nonreg-tests_windows-latest-msvc

on:
  # Permit calling trigger
  workflow_call:
  # Activate the workflow at each push on main branch
  #push:
  #  branches: [ main ]
  # Activate the workflow at each pull request on main branch
  #pull_request:
  #  branches: [ main ]
  # Permit manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  CMAKE_BUILD_TYPE : Release
  BUILD_DIR : build
  CMAKE_GENERATOR : Ninja
  PYTHON_VERSION : "3.13.3"
  CMAKE_TOOLCHAIN_FILE : C:\vcpkg\scripts\buildsystems\vcpkg.cmake
  
jobs:

  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        echo '{
          "dependencies": [ "boost-math", "boost-filesystem" ],
          "builtin-baseline": "d5ec528843d29e3a52d745a64b469f810b2cedbf"
        }' > vcpkg.json
        vcpkg install

    - name: Setup uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{env.PYTHON_VERSION}}
        activate-environment: true

    - name: Install python dependencies
      run: |
        uv pip install numpy

    - name: Set up Visual Studio shell
      uses: egor-tensin/vs-shell@v2

    - name: Configure build directory
      run: |
        cmake `
          -B${{ env.BUILD_DIR }} `
          -DBUILD_PYTHON=ON

    - name: Build the package
      run: |
        cmake --build ${{env.BUILD_DIR}} --parallel 3 --config ${CMAKE_BUILD_TYPE}

    - name: Install packages and execute non-regression tests
      run: |
        cmake --build ${{env.BUILD_DIR}} --target check --config ${CMAKE_BUILD_TYPE}

    - name: Compress output logs
      if: success() || failure()
      shell: powershell
      run: |
        cd ${{env.BUILD_DIR}}/tests
        Get-ChildItem -Recurse -Filter '*.out' | Select-Object -ExpandProperty Fullname | Resolve-Path -Relative > logs.txt
        foreach ($filename in Get-Content .\logs.txt)
        {
            Compress-Archive -Update $filename .\msvc-logs.zip
        }

    - name: Publish output logs as artefact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: msvc-nonreg-logs
        path: ${{env.BUILD_DIR}}/tests/msvc-logs.zip

